<?php
/**
 * @file
 * Code for the Getty Image feature.
 */

include_once 'image_node.features.inc';

/**
 * Implements hook_init().
 */
function image_node_init() {
  if (arg(0) == 'project' && is_numeric(arg(1)) && arg(2) == 'images' && !empty($_GET['u'])) {
    drupal_set_message(t('Uploaded @count images successfully.', array('@count' => (int) $_GET['u'])));
    drupal_goto('project/' . arg(1) . '/images');
  }
}

/**
 * Implements hook_views_pre_view().
 */
function image_node_views_pre_view(&$view) {
  if ($view->name == 'images' && $view->current_display == 'page_1') {
    $project_nid = arg(1);
    if (og_user_access('node', $project_nid, 'create image content')) {
      $view->attachment_before = l(t('Upload images'), "project/$project_nid/images/upload");
    }
  }
}

function image_node_menu() {
  $items['project/%/images/upload'] = array(
    'title' => 'Upload Images',
    'page callback' => 'upload_images_page',
    'page arguments' => array(1),
    'access callback' => 'og_user_access',
    'access arguments' => array('node', 1, 'create image content'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function image_node_theme($existing, $type, $theme, $path) {
  return array(
    'upload_images_page' => array(
      'template' => 'upload_images_page',
    ),
  );
}

function upload_images_page($project_nid) {
  if (!empty($_FILES)) {
    // Ajax form save
    $count = count($_FILES['files']['name']);
    $saved_nodes = 0;
    foreach (range(0, $count - 1) as $i) {
      $file = file_save_upload($i, NULL, 'public://');
      $file->status = 1;
      file_save($file);

      $node = new stdClass();
      $node->is_new = TRUE;
      $node->type = 'image';
      $node->language = LANGUAGE_NONE;
      node_object_prepare($node);
      $node->title = $_POST['title'][$i];
      $node->field_image['und'][0] = (array) $file;
      if (!empty($_POST['creator'][$i])) $node->field_creator['und'][0]['value'] = $_POST['creator'][$i];
      if (!empty($_POST['creation_date'][$i])) $node->field_object_creation_date['und'][0]['value'] = $_POST['creation_date'][$i];
      if (!empty($_POST['medium'][$i])) $node->field_medium['und'][0]['value'] = $_POST['medium'][$i];
      if (!empty($_POST['dimensions'][$i])) $node->field_dimensions['und'][0]['value'] = $_POST['dimensions'][$i];
      if (!empty($_POST['location'][$i])) $node->field_location['und'][0]['value'] = $_POST['location'][$i];
      if (!empty($_POST['description'][$i])) $node->field_description['und'][0]['value'] = $_POST['description'][$i];
      $node->og_group_ref['und'][0]['target_id'] = $project_nid;
      node_save($node);
      if ($node->nid) $saved_nodes++;
    }
    drupal_json_output(array( "message" => "Successfully uploaded $saved_nodes images. " . l(t('Click here to continue.'), "project/$project_nid/images") ));
    drupal_exit();
  }

  // Form not yet submitted.
  drupal_add_css(drupal_get_path('module', 'image_node') . '/upload_images_page.css');
  drupal_add_js(drupal_get_path('module', 'image_node') . '/upload_images_page.js');
  return theme('upload_images_page');
}
