<?php
/**
 * @file
 * Code for the Getty Comparison feature.
 */

include_once 'comparison_node.features.inc';

/**
 * Implements hook_menu().
 */
function comparison_node_menu() {
  $items = array();
  $items['modal/comparison/%node'] = array(
    'title callback' => 'node_page_title',
    'title arguments' => array(2),
    'page callback' => 'comparison_modal_page',
    'page arguments' => array(2),
    'access callback' => 'node_access',
    'access arguments' => array('view', 2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function comparison_modal_page($node) {
  drupal_add_css('
    #admin-menu,
    #section-header {
      display: none;
    }
  ', 'inline');
  $content = node_view($node);
  return render($content['field_image_reference_info']);
}

/**
 * Implements hook_views_pre_view().
 */
function comparison_node_views_pre_view(&$view) {
  if ($view->name == 'comparisons' && $view->current_display == 'page') {
    $project_nid = arg(1);
    if (og_user_access('node', $project_nid, 'create comparison content')) {
      $view->attachment_before = l(t('Add new comparison'), "project/$project_nid/lighttable");
    }
  }
}

