<?php
/**
 * @file
 * timeline.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function timeline_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-timeline_date-body'.
  $field_instances['node-timeline_date-body'] = array(
    'bundle' => 'timeline_date',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Event Summary',
    'required' => 0,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 4,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-timeline_date-field_image_caption'.
  $field_instances['node-timeline_date-field_image_caption'] = array(
    'bundle' => 'timeline_date',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_image_caption',
    'label' => 'Image Caption',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-timeline_date-field_image_credit'.
  $field_instances['node-timeline_date-field_image_credit'] = array(
    'bundle' => 'timeline_date',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_image_credit',
    'label' => 'Image Credit',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-timeline_date-field_timeline_end_date'.
  $field_instances['node-timeline_date-field_timeline_end_date'] = array(
    'bundle' => 'timeline_date',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Note: BCE dates can be entered by placing a minus sign (-) before the year. Years between -9999 and 9999 are supported.',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'partial_date',
        'settings' => array(
          'component_settings' => array(
            'components' => array(
              'approx' => array(
                'value' => '',
                'weight' => -1,
              ),
              'c1' => array(
                'value' => '',
                'weight' => 7,
              ),
              'c2' => array(
                'value' => '',
                'weight' => 8,
              ),
              'c3' => array(
                'value' => '',
                'weight' => 9,
              ),
              'day' => array(
                'empty' => '',
                'format' => 'd',
                'weight' => 2,
              ),
              'hour' => array(
                'empty' => '',
                'format' => 'H',
                'weight' => 3,
              ),
              'minute' => array(
                'empty' => '',
                'format' => 'i',
                'weight' => 4,
              ),
              'month' => array(
                'empty' => '',
                'format' => 'm',
                'weight' => 1,
              ),
              'second' => array(
                'empty' => '',
                'format' => 's',
                'weight' => 5,
              ),
              'timezone' => array(
                'empty' => '',
                'format' => 'T',
                'weight' => 6,
              ),
              'year' => array(
                'empty' => '',
                'format' => 'Y-ce',
                'weight' => 0,
              ),
            ),
            'display' => array(
              'day' => 'date_or',
              'hour' => 'date_or',
              'minute' => 'date_or',
              'month' => 'date_or',
              'second' => 'date_or',
              'timezone' => 'date_only',
              'year' => 'date_or',
            ),
            'meridiem' => 'a',
            'separator' => array(
              'date' => '-',
              'datetime' => ' ',
              'other' => ' ',
              'range' => '',
              'time' => ':',
            ),
            'year_designation' => 'sign',
          ),
          'field_formatter_class' => '',
          'format' => 'long',
          'use_override' => 'none',
        ),
        'type' => 'partial_date_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_timeline_end_date',
    'label' => 'End Date',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'partial_date',
      'settings' => array(
        0 => FALSE,
        'estimates' => array(
          'from' => array(
            'day' => 0,
            'hour' => 0,
            'minute' => 0,
            'month' => 0,
            'second' => 0,
            'year' => 0,
          ),
        ),
        'granularity' => array(
          'from' => array(
            'day' => 'day',
            'hour' => 0,
            'minute' => 0,
            'month' => 'month',
            'second' => 0,
            'timezone' => 0,
            'year' => 'year',
          ),
        ),
        'help_txt' => array(
          'und' => array(
            '_remove' => '',
            'check_approximate' => '',
            'components' => '',
            'txt_long' => 'Longer description of date',
            'txt_short' => 'Short description of date',
          ),
        ),
        'hide_remove' => 0,
        'increments' => array(
          'minute' => 1,
          'second' => 1,
        ),
        'theme_overrides' => array(
          'check_approximate' => 0,
          'range_inline' => 0,
          'txt_long' => 0,
          'txt_short' => 0,
        ),
        'tz_handling' => 'none',
      ),
      'type' => 'partial_date',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-timeline_date-field_timeline_media_image'.
  $field_instances['node-timeline_date-field_timeline_media_image'] = array(
    'bundle' => 'timeline_date',
    'deleted' => 0,
    'description' => 'This is the image that will appear on the timeline.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'field_formatter_class' => '',
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'field_formatter_class' => '',
          'image_link' => '',
          'image_style' => 'thumbnail',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_timeline_media_image',
    'label' => 'Timeline Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => 'timeline_images',
      'file_extensions' => 'png gif jpg jpeg',
      'image_field_caption' => 0,
      'image_field_caption_wrapper' => array(
        'image_field_caption_default' => array(
          'format' => 'full_html',
          'value' => '',
        ),
      ),
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-timeline_date-field_timeline_start_date'.
  $field_instances['node-timeline_date-field_timeline_start_date'] = array(
    'bundle' => 'timeline_date',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Note: BCE dates can be entered by placing a minus sign (-) before the year. Years between -9999 and 9999 are supported.',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'partial_date',
        'settings' => array(
          'component_settings' => array(
            'components' => array(
              'approx' => array(
                'value' => '',
                'weight' => -1,
              ),
              'c1' => array(
                'value' => '',
                'weight' => 7,
              ),
              'c2' => array(
                'value' => '',
                'weight' => 8,
              ),
              'c3' => array(
                'value' => '',
                'weight' => 9,
              ),
              'day' => array(
                'empty' => '',
                'format' => 'd',
                'weight' => 2,
              ),
              'hour' => array(
                'empty' => '',
                'format' => 'H',
                'weight' => 3,
              ),
              'minute' => array(
                'empty' => '',
                'format' => 'i',
                'weight' => 4,
              ),
              'month' => array(
                'empty' => '',
                'format' => 'm',
                'weight' => 1,
              ),
              'second' => array(
                'empty' => '',
                'format' => 's',
                'weight' => 5,
              ),
              'timezone' => array(
                'empty' => '',
                'format' => 'T',
                'weight' => 6,
              ),
              'year' => array(
                'empty' => '',
                'format' => 'Y-ce',
                'weight' => 0,
              ),
            ),
            'display' => array(
              'day' => 'date_or',
              'hour' => 'date_or',
              'minute' => 'date_or',
              'month' => 'date_or',
              'second' => 'date_or',
              'timezone' => 'date_only',
              'year' => 'date_or',
            ),
            'meridiem' => 'a',
            'separator' => array(
              'date' => '-',
              'datetime' => ' ',
              'other' => ' ',
              'range' => '',
              'time' => ':',
            ),
            'year_designation' => 'sign',
          ),
          'field_formatter_class' => '',
          'format' => 'long',
          'use_override' => 'none',
        ),
        'type' => 'partial_date_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_timeline_start_date',
    'label' => 'Start Date',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'partial_date',
      'settings' => array(
        0 => FALSE,
        'estimates' => array(
          'from' => array(
            'day' => 0,
            'hour' => 0,
            'minute' => 0,
            'month' => 0,
            'second' => 0,
            'year' => 0,
          ),
        ),
        'granularity' => array(
          'from' => array(
            'day' => 'day',
            'hour' => 0,
            'minute' => 0,
            'month' => 'month',
            'second' => 0,
            'timezone' => 0,
            'year' => 'year',
          ),
        ),
        'help_txt' => array(
          'und' => array(
            '_remove' => '',
            'check_approximate' => '',
            'components' => '',
            'txt_long' => 'Longer description of date',
            'txt_short' => 'Short description of date',
          ),
        ),
        'hide_remove' => 0,
        'increments' => array(
          'minute' => 1,
          'second' => 1,
        ),
        'theme_overrides' => array(
          'check_approximate' => 0,
          'range_inline' => 0,
          'txt_long' => 0,
          'txt_short' => 0,
        ),
        'tz_handling' => 'none',
      ),
      'type' => 'partial_date',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-timeline_date-og_group_ref'.
  $field_instances['node-timeline_date-og_group_ref'] = array(
    'bundle' => 'timeline_date',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'og_group_ref',
    'label' => 'Groups audience',
    'required' => 0,
    'settings' => array(
      'behaviors' => array(
        'og_widget' => array(
          'access_override' => 0,
          'admin' => array(
            'widget_type' => 'entityreference_autocomplete',
          ),
          'default' => array(
            'widget_type' => 'options_select',
          ),
          'status' => TRUE,
        ),
      ),
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'og',
      'settings' => array(),
      'type' => 'og_complex',
      'weight' => 7,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('End Date');
  t('Event Summary');
  t('Groups audience');
  t('Image Caption');
  t('Image Credit');
  t('Note: BCE dates can be entered by placing a minus sign (-) before the year. Years between -9999 and 9999 are supported.');
  t('Start Date');
  t('This is the image that will appear on the timeline.');
  t('Timeline Image');

  return $field_instances;
}
