<?php
/**
 * @file
 * Code for the essay_node feature.
 */

include_once 'essay_node.features.inc';

/**
 * Implements hook_menu().
 */
function essay_node_menu() {
  $items['project/%/essays'] = array(
    'title' => 'Essays',
    'title callback' => 'essay_node_page_title_callback',
    'page callback' => 'views_embed_view',
    'page arguments' => array('essays', 'block_essays_list', 1),
    'access callback' => 'og_user_access',
    'access arguments' => array('node', 1, 'unsubscribe'),
  );

  return $items;
}

function essay_node_page_title_callback($title) {
  $gid = arg(1);
  $group = node_load($gid);

  return $group->title . ' ' . $title;
}

/**
 * Implements hook_views_pre_view().
 */
function essay_node_views_pre_view(&$view) {
  if ($view->name == 'essays' && $view->current_display == 'block_essays_list') {
    $project_nid = arg(1);
    if (og_user_access('node', $project_nid, 'create essay content')) {
      $view->attachment_before = l(t('Add new essay'), "node/add/essay/$project_nid");
    }
  }
}

